-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 15:49:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EjemploDiagrama
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EjemploDiagrama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EjemploDiagrama` DEFAULT CHARACTER SET utf8 ;
USE `EjemploDiagrama` ;

-- -----------------------------------------------------
-- Table `EjemploDiagrama`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploDiagrama`.`CLIENTES` (
  `NIT` INT NULL,
  `ID_CLIENTES` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO` VARCHAR(45) NULL,
  `DIRECCIÓN` VARCHAR(45) NULL,
  `NIT` INT NULL,
  `TELÉFONO` INT NULL,
  PRIMARY KEY (`ID_CLIENTES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploDiagrama`.`FACTURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploDiagrama`.`FACTURAS` (
  `ID_FACTURAS` INT NOT NULL,
  `FECHA` DATE NULL,
  `CLIENTES_ID_CLIENTES` INT NOT NULL,
  PRIMARY KEY (`ID_FACTURAS`),
  INDEX `fk_FACTURAS_CLIENTES_idx` (`CLIENTES_ID_CLIENTES` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURAS_CLIENTES`
    FOREIGN KEY (`CLIENTES_ID_CLIENTES`)
    REFERENCES `EjemploDiagrama`.`CLIENTES` (`ID_CLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploDiagrama`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploDiagrama`.`PRODUCTOS` (
  `ID_PRODUCTOS` INT NOT NULL,
  `NOMBRE DEL PRODUCTO` VARCHAR(45) NULL,
  `DESCRIPCIÓN` VARCHAR(45) NULL,
  `PRECIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PRODUCTOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EjemploDiagrama`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EjemploDiagrama`.`VENTAS` (
  `ID_VENTAS` INT NOT NULL,
  `CANTIDAD` INT NULL,
  `FACTURAS_ID_FACTURAS1` INT NOT NULL,
  `PRODUCTOS_ID_PRODUCTOS` INT NOT NULL,
  PRIMARY KEY (`ID_VENTAS`, `FACTURAS_ID_FACTURAS1`, `PRODUCTOS_ID_PRODUCTOS`),
  INDEX `fk_VENTAS_FACTURAS2_idx` (`FACTURAS_ID_FACTURAS1` ASC) VISIBLE,
  INDEX `fk_VENTAS_PRODUCTOS1_idx` (`PRODUCTOS_ID_PRODUCTOS` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_FACTURAS2`
    FOREIGN KEY (`FACTURAS_ID_FACTURAS1`)
    REFERENCES `EjemploDiagrama`.`FACTURAS` (`ID_FACTURAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_ID_PRODUCTOS`)
    REFERENCES `EjemploDiagrama`.`PRODUCTOS` (`ID_PRODUCTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
